### ISSUE TITLE
right-clicking (placing) blocks or plants only places one and then the rest of the stack disappears on version A6

### ISSUE THREAD

**Issue by xxicemannxx** [Flo56958/MineTinker#10]
**Describe the bug**
when trying to place blocks or plant seeds, it will place one item and then the rest of the selected stack disappears from inventory.

**Expected behavior**
This was working prior to upgrading to v A6

**Server (please complete the following information):**
- Plugin-Version  A6
- only other plugins that I have installed are Chair Stairs (latest), PermissionsEX (latest) and Vault 1.5.6
- Using latest Spigot 1.13 build.

**Additional context**
I reverted back to A5 and the function returned to normal.

**Comment by Flo56958** [comment]
@xxicemannxx 
I fixed the bug in version a6.1. It was a mistake on my part. I arranged two lines in the wrong order and the plugin sets the Stacksize to 1 before placing a block. 
Thanks for the Bugreport!

Sincerely,
Flo56958
