### ISSUE TITLE
Better shear support

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#104]
**Is your feature request related to a problem? Please describe.**
Power can go on shears but this doesn't accomplish much and feels terrible to use.

**Describe the solution you'd like**
Better integration of Power or an alternate form of EasyHarvest for shears.
A few of my players could be interested in gathering leaves with power shears.
Maybe right clicking with power shears would remove all leaves from a tree and drop them on the ground?

**Comment by Flo56958** [comment]
Power would then be a Timber-Leaves-Modifier on shears?

**Comment by Flo56958** [comment]
Timber on Shears will break all leaves when a leave block is broken
