### ISSUE TITLE
Power + Hoe and tilling ground

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#112]
Players often request to be able to till ground 5x5 with power 3 hoes.
A lot of players ask about this when they first get power hoes, too.

I think it would be a good addition.

**Comment by Flo56958** [comment]
https://github.com/Flo56958/MineTinker/blob/d4f1ce6205fb08157d5f2d6ab7e630b9a6ba55b7/core/src/main/java/de/flo56958/MineTinker/Modifiers/Types/Power.java#L349-L366

Should already be a thing. Seams to be bugged....

**Comment by Draycia** [comment]
I'll look into it soon today since I don't have any other plans

**Comment by Draycia** [comment]
Yeah I'm not seeing the powerCreateFarmland method ever being triggered, when right clicking grass with the hoe.

**Comment by Draycia** [comment]
Found the issue

**Comment by Draycia** [comment]
Fixed in 336fa48e843caefc1e9cf2bbd6ecc3b7e459b925
