### ISSUE TITLE
Plugin no longer unregisters old recipes on reload

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#113]
![image](https://user-images.githubusercontent.com/15833072/63301006-63fa3f80-c28e-11e9-9067-c7499ccbe51c.png)

**Comment by Flo56958** [comment]
![image](https://user-images.githubusercontent.com/13511426/64469038-bdb99100-d0f9-11e9-8c80-1a3b218b628a.png)
I don't know why but the Loop skips a lot of recipes...

Code that was tested and gave the output: 
```java
        Iterator<Recipe> it = Main.getPlugin().getServer().recipeIterator(); //TODO: Better algorithm for removing recipes from modifiers

        System.out.println(1);
        int i = 1;
        while (it.hasNext()) {
            System.out.println(++i);
            Recipe rec = it.next();
            ItemStack result = rec.getResult();

            if (result.getType() != Material.EXPERIENCE_BOTTLE && result.getType() == Material.NETHER_STAR) {
                System.out.println(result);
                System.out.println(result.getType());
                //Modifieritems
                if (modManager.isModifierItem(result)) {
                    it.remove();
                }

                //Builderswands
                else if (modManager.isWandViable(result)) {
                    it.remove();
                }
            }
        }
```

I have improved the checking of the recipes but if almost all of them are skipped then it does not change anything...

**Comment by JJBlue** [comment]
Problem solved(?):
It is not skipping. The console output is missing some Message. If you write it into a File, you see what it isn't skipping.


        try {
		FileWriter writer = new FileWriter(new File("./plugins/test.yml"));
	        int i = 1;
	        while (it.hasNext()) {
	        	++i;
	        	writer.append(i + "\n");
	            System.out.println(i);
	            Recipe rec = it.next();
	            ItemStack result = rec.getResult();
	
	            if (result.getType() != Material.EXPERIENCE_BOTTLE && result.getType() == Material.NETHER_STAR) {
	                System.out.println(result);
	                System.out.println(result.getType());
	            }
	        }
	        
	        writer.close();
         } catch (IOException e) {
			e.printStackTrace();
         }
`

**Comment by JJBlue** [comment]
I looked at the Code and it looks as if "it.remove()" does not yield the desired goal.
Test Code equals to the Minecraft/Bukkit Code.

		Map<String, Map<String, String>> mapy = new HashMap<>();
		HashMap<String, String> tmp = new HashMap<>();
		tmp.put("1", "1");
		tmp.put("2", "2");
		mapy.put("a", tmp);
		
		tmp = new HashMap<>();
		tmp.put("10", "10");
		tmp.put("20", "20");
		mapy.put("b", tmp);
		
		Iterator<String> it = mapy.values().stream().flatMap((map) -> {
			return map.values().stream();
		}).collect(Collectors.toSet()).iterator();
		
		if(it.hasNext()) {
			it.next();
			it.remove();
		}
		
		for(String key1 : mapy.keySet()) {
			Map<String, String> map2 = mapy.get(key1);
			
			for(String key2 : map2.keySet()) {
				System.out.println(key1 + " " + key2 + " " + map2.get(key2));
			}
		}

Output:
a 1 1
a 2 2
b 20 20
b 10 10

Result: Does not work as you wish
