### ISSUE TITLE
EliteMobs Compatibility

### ISSUE THREAD

**Issue by DerMongoose** [Flo56958/MineTinker#116]
**Is your feature request related to a problem? Please describe.**
I noticed that the MineTinker Weapons and Armors have serious problems going against Elite mobs from the EliteMobs addon, as Elite mobs will deal lots of damage through armor, which makes it really risky to run around in MineTinker armor. 

**Describe the solution you'd like**
Perhaps a compatability addon that adds a modifier that applies the Elite Sharpness, Power, or Protection to MineTinker items, as well as a modifier for the Hunter and for the Critical Strikes enchants.  An example of a modifier item and it's corresponding modifier would be right-clicking a gold ingot on a bookshelf to get an Enchanted Gold Ingot for the Elite's Bane modifier.

**Describe alternatives you've considered**
Nope, haven't really considered anything else that wouldn't be overpowered.

**Additional context**
A server I play on has both MineTinker and EliteMobs, and usually in a crowd of mobs I would stumble upon an Elite or two, which I would either have to retreat from or fight alone, as all the other mobs would give an advantage to the elite, elites also deal a lot of damage and have a lot of health, which can be mitigated through EliteMobs weapons, but not through MineTinker weapons. It would be a nice quality of life addition to make it so I don't require two melee weapons in my inventory, and especially when one is made of gold and easily breaks.

**Comment by sjackser** [comment]
As an ordinary player, should I say that the EliteMobs enhancements should be on EliteMobs part, not on MineTinker? Since the former one's dev said they will add support to upgrading armors thru various methods or something...

**Comment by DerMongoose** [comment]
Oh, cool then, perhaps the developers of both addons can work together to figure something out that is reasonably balanced.

**Comment by Flo56958** [comment]
I am open to working together with another developer. But atm i wont contact anyone myself to make plugin compatibilities to MT. If someone contacts me with that topic i will be happy to help and develop with them. Currently i am trying to develop and finish version 1.1.
