### ISSUE TITLE
Self-repair X makes Self-repair not work at all (possibly unbreaking)

### ISSUE THREAD

**Issue by Moogsl** [Flo56958/MineTinker#134]
When an item gets to Self-repair X the durability starts dropping DRASTICALLY as if neither unbreaking or self-repair work at all

**Comment by Flo56958** [comment]
Not recreatable on my end. Are you using Mending as Self-Repair?

**Comment by Moogsl** [comment]
Was an item converted from mending to self-repair. Item worked fine at
VIII, didn't test for IX but it definitely doesn't work at X.
