### ISSUE TITLE
Magical Enchantment Lore Appears on Bows Multiple Times

### ISSUE THREAD

**Issue by tutuw002** [Flo56958/MineTinker#135]
**Description**
The "Magical" enchantment lore appears on a bow/crossbow multiple times when enchanting it with an anvil.

**Server information**
 - Plugin Version: 1.3.2
 - Server Version: 1.15.2 Paper

![Anvil](https://i.imgur.com/gB2PEuu.png)
![Anvil](https://i.imgur.com/5UtXM13.png)
![Bow](https://i.imgur.com/RcVvQcs.png)
![Bow](https://i.imgur.com/QOivGUw.png)

**Comment by tutuw002** [comment]
Not found on "vanilla" server, closing

**Comment by Flo56958** [comment]
Do you have the Pattern Matcher enabled? Idk why but that issue is most likely because of that
