### ISSUE TITLE
Possibility to customize the translation of the plugin

### ISSUE THREAD

**Issue by AerWyn81** [Flo56958/MineTinker#138]
**Is your feature request related to a problem? Please describe.**
I wish to customize format on the messages sent on the players chat like many plugins with a custom translation file.

**Describe the solution you'd like**
Have the possibility to have an accessible translation file or be able to extract it from the plugin.

**Describe alternatives you've considered**
I tried to extract the translation file but it didn't work or maybe I just didn't see that it was possible ?

Edit from @Flo56958:
- [x] Restructure the LanguageManager so that every language file is a default file
- [x] copy all default files into the plugin folder under the folder "lang"
- [x] read language lines from the resource folder instead of from inside the jar
- [ ] when #150:
     - Change the LanguageManager from static to Singleton
     - Have a abstract Manager Class to have a better implementation for all 4 Managers (Item-, Tool-, Configuration-, Language-) [at least the reload-Listener will be the same for all]

**Comment by Flo56958** [comment]
You could extract the language file with WinRar change it and put it back.
And many lines can be changed in the config.
If you are talking about the english language: I am not the best at english language and you can help me improve it if you like.
If you are talking about a different language: You can review the language on Transifex and make improvements to it if you like.

**Comment by AerWyn81** [comment]
Thank you, I hadn't thought of doing that manipulation.

However, when updating the plugin, if you add translations, it might complicate the task of updating. Hence the idea of having a file at the root of the configuration files where translations would be added at the end at each update.

I've seen transipex, the problem is not that I don't want to share my translations haha, it's more in the idea of formatting the translations according to a particular design for my server.
