### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by katalinea** [Flo56958/MineTinker#14]
**Describe the bug**
My console gets spammed with an error whenever people use tools, and some tools wont gain exp. It's not consistent.

**To Reproduce**
1. Use a tinker-tool
2. See error (if there is an error in console please post it after your issue)

**Expected behavior**
Gain exp on tools and not get an error message

**Screenshots**
My plugins, incase any are interfering. 
![pl](https://user-images.githubusercontent.com/40867541/44951185-fa85e480-ae22-11e8-8395-5c67d9cdce05.PNG)

**Server (please complete the following information):**
- 6.2.1
- I don't think any of my plugins are interfering, but it's possible 

**Additional context**
Here's the error message in a text file
[Error.txt](https://github.com/Flo56958/MineTinker/files/2342894/Error.txt)

**Comment by Flo56958** [comment]
@katalinea
It seams like 1.13.1 is totally not supported atm. Am I seeing something wrong or do you use Paperspigot? It could also be that this is the problem maker. Have you tried Spigot 1.13.1 (never tested Paper)? The plugin runs on some servers with this version but you are the first to mention this (as I see it mayor) problem.
Flo56958

**Comment by katalinea** [comment]
Yeah, I do use Paper. I tried testing Spigot, and I still received the error. I'm not quite sure how major this issue actually is, seeing as how it's only been reported a few times. It seems that some tools are gaining exp, and some aren't. From what I can tell there is not common denominator. Also, some of the tools that aren't gaining exp are also having issued with modifiers like glowing and poisonous, but other tools are supporting these modifiers just fine. There seems to be no consistency with which type of tools are having issues, nor with which modifiers aren't working
