### ISSUE TITLE
MineTinkers broken with Slimefun tools, armour, and weapons

### ISSUE THREAD

**Issue by JustPixeled** [Flo56958/MineTinker#151]
**Describe the bug**
Slimefun tools, armour, and weapons can be turned into Minetinkers tools but when you try to remove any modifiers from the item you get given the modifier items but the modifiers stay on the Slimefun tool.

**To Reproduce**
1. Obtain a Slimefun tool/weapon/armour that has enchantments
2. mine a block/hit an enemy/damage the amour and it will become a MineTinkers item with modifiers
3. Then try to remove the modifiers using a grindstone and you will be given modiers as items but won't be cleared from the tool meaning you can infinately obtain modiefier items

**Expected behavior**
All modiefiers that come with the Slimefun item should stay whilst other modifiers that you apply should be able to be removed when used in a grindstone

**Video Detail**
https://youtu.be/2srQG0VuGX8

**Information about the server (please complete the following information):**
 - MineTinkers Version: Version 1.5.2
 - Slimefun Version:  Slimefun4 - DEV 543 (git f0b5d)
 - Server Version: CraftBukkit version git-Spigot-a99063f-c9d7c16 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
 - Plugins: LuckPerms, MineTinker, ColoredSigns, FastLeafDecay, ClearLag, mcMMO, CS-CoreLib, Vault, GriefPrevention, ColoredAnvils, Slimefun, Essentials, CrazyAuctions, EssentialsChat, Jobs

**Additional context**
After some testing I have discovered that it is MineTinkers 1.5.2 that intriduces this bug

**Comment by Flo56958** [comment]
Seams like Slimefun cancelled the event after MT did its stuff. Idk Slimefun so does Slimefun deny grindstone events for some tools?

**Comment by Flo56958** [comment]
Maybe we need to bump up the EvenPriority of the GrindstoneListener

**Comment by JustPixeled** [comment]
It has affected all Slimefun tools, weapons, and armour that I've tested so far, it also affects modifiers that you apply after it becoming a MineTinkers tool.

![MineTinkers Slimefun Bug](https://user-images.githubusercontent.com/56881532/84884422-9b41a480-b089-11ea-8ea5-8dbff49df2ff.gif)

**Comment by JustPixeled** [comment]
Do you have any updates on this issue? One of the only things stopping me from updating my server to 1.16 is this bug.

**Comment by Flo56958** [comment]
Seems like a bigger incompatibility. MT can not check if the tool is from Slimefun, so it only treats it like a MT-Tool. You could try to disable the Conversion of the tools. So you have separate tools from MT and SF.

**Comment by JustPixeled** [comment]
It turns into a MineTinkers tool when you damage the item, Idk what config would change that

**Comment by Flo56958** [comment]
ItemBehaviour.ConvertItemsOnUse
