### ISSUE TITLE
AllowEnchanting can be used to get unlimited quantity of modifiers.

### ISSUE THREAD

**Issue by Ink-33** [Flo56958/MineTinker#158]
**Describe the bug**
When AllowEnchanting is true, player can use a enchanted book in anvil to get unlimited quantity of modifiers.

**To Reproduce**
1. Go to anvil.
2. Put an item that can be enchanted, and put the enchanted book .
3. Take off the item
4. See error. A free modifier will be given.

**Expected behavior**
No free modifiers will be given.

**Vedios**
see [here](https://api.smlk.org/mirror/ink33/mtbugs.mp4)

**Information about the server (please complete the following information):**
 - Plugin Version
MineTinker 1.6 (c1dbb09b83962b6a41cc29273660e9b0b0a20e68)
 - Server Version
This server is running Paper version git-Paper-"81f6d51f0" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
 - other Plugins
Plugins (42): Barrels, BlocksHub, ClearNBT, ClientStats*, ClientStatsSaver*, CoreProtect, CS-CoreLib, DeathBarrel, Elevator*, Essentials, floodgate-bukkit, Geyser-Spigot, InteractionVisualizer, JukeBox, LightAPI, LiveBot, LuckPerms, mcMMO, MineTinker, MOTD, NoteBlockAPI, PlaceholderAPI, PluginManager*, ProtocolLib, QQMinecraft*, SAML, ServerMSPT, Slimefun, SmoothSleep, spark, TitleManager, Towny, TownyChat, TownyNameUpdater, TownyTitle*, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, WorldBorder, WorldEdit, XPConomy
**Additional context**
 - Console log(I don't have the access to the console.)
The bugs will no longer exist if set AllowEnchanting to false.

English is not my native language,and please excuse typing errors.

**Comment by ishland** [comment]
There is no error spamming in the console

**Comment by notBuiden** [comment]
我的临时解决方法是：
allowcrafting设置为false，allowconvert设置为true这样从工作台里做出的工具是原版工具，原版工具（含附魔）需要放入工作台转换才能变成mt工具
allowenchantment好像是这样的吧我也设置为false，这样子mt工具无法附魔
这样就做到了原版和mt两套锻造系统并行！！
