### ISSUE TITLE
Cannot craft modifiers until /mt reload is invoked

### ISSUE THREAD

**Issue by ishland** [Flo56958/MineTinker#159]
**Describe the bug**
Cannot craft modifiers until /mt reload is invoked

**To Reproduce**
Steps to reproduce the behavior
0. Start the server and join
1. Try to craft modifiers
2. Nope
3. Invoke /mt reload
4. Try again

**Expected behavior**
Modifiers should be craftable whenever MineTinker is installed

**Screenshots**
Nope

**Information about the server (please complete the following information):**
 - Plugin Version `MineTinker 1.6` ed1b54ea78d7ac651e3ee90a4c37e6f2a09a3a97
 - Server Version `This server is running Paper version git-Paper-"9788250b1" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`
 - other Plugins `Plugins (44): Barrels, BasicCircuitBoardRecipe, BlocksHub, ClearNBT, ClientStats*, ClientStatsSaver*, CoreProtect, CS-CoreLib, DeathBarrel, Elevator*, Essentials, floodgate-bukkit, Geyser-Spigot, InteractionVisualizer, JukeBox, LightAPI, LiveBot, LuckPerms, mcMMO, MineTinker, MOTD, NoteBlockAPI, PlaceholderAPI, PluginManager*, ProtocolLib, QQMinecraft*, SAML, SandtoQuartz, ServerMSPT, Slimefun, SmoothSleep, spark, TitleManager, Towny, TownyChat, TownyNameUpdater, TownyTitle*, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, WorldBorder, WorldEdit, XPConomy`

**Additional context**
 - Console log Nope

**Comment by Flo56958** [comment]
was it the first startup?
or also on other startups?

**Comment by ishland** [comment]
on every startup

**Comment by ishland** [comment]
It seems like the recipe didn't get registered at startup but on reload

**Comment by liv-kami** [comment]
is there an error on initial startup?

**Comment by ishland** [comment]
> is there an error on initial startup?

No error printed at startup

**Comment by Flo56958** [comment]
One thought: Could be that a plugin negates custom recipes until the server is started.
Does /mt mods show the recipes after startup?

**Comment by ishland** [comment]
> Does /mt mods show the recipes after startup?

Yes it does show recipes but unusable in crafting tables.

**Comment by Flo56958** [comment]
Do you still have this issues with a newer version of MT or Minecraft?

**Comment by Dalethium** [comment]
I can confirm this is present on 1.16.4 and mine tinker 1.6.2, at least it works with the reload though. 
I believe it was working before, but after some updated plugins it stopped working. I've attached a screenshot of my most recently added/updated plugins.
![SX-All-KG8kI2PEeV-2106](https://user-images.githubusercontent.com/22735418/107412554-0a37a600-6b10-11eb-8ae8-2fc7bc807174.png)

https://timings.aikar.co/?id=0476118a124144b1b477a89cdeb73df2 - here is my timings report for general debug info about my server
My configs for MT
[MineTinker.zip](https://github.com/Flo56958/MineTinker/files/5953626/MineTinker.zip)
