### ISSUE TITLE
modifiers appearing out of nowhere

### ISSUE THREAD

**Issue by Vexiusnetwork** [Flo56958/MineTinker#169]
**Describe the bug**
MT Modifiers apepar out of nowhere in yoru inv when anchanting

**To Reproduce**
1. get a vanilla tool like a pick - ive tried pick, spade, axe and sword
2, get a vanilla ebook like Eff5, Silk or Mending, ive tried all three
3. apply book to tool on anvil
4. as you take tool out of anvil, the correspoinding MY Modifiers appear i nyou inv - if you applky Effciency 5, you get 5 Haste mods, Silk gets you and enchanted cobweb, mending gets you a Self respir mod.
5, Proof: disable Mintinker, it doesnt happen.

**Information about the server (please complete the following information):**
 - Plugin Version 1.16.2 
 - Server Version 1.16.3
 - other Plugins
lots, the relevant one is slimefun, but thats not affectig it.

**Comment by Vexiusnetwork** [comment]
why has this been closed? is there a known fix ?

**Comment by Flo56958** [comment]
it has nothing to do with slimefun, MT just forgot to check if the tool is a MT one or not; the mentioned commit ads the check for a MT Tool in the anvil

**Comment by Vexiusnetwork** [comment]
yes, its a minetinker issue.  it needs fixing. you are Flo56958/Minetinker.  So whats the solution?

If the buck doesnt stop with minetinker on Github, wher does it stop ?



________________________________
