### ISSUE TITLE
support for Korean translation

### ISSUE THREAD

**Issue by sooyeon73** [Flo56958/MineTinker#170]
Hello,
In order to help Korean users use Minetinker, I completed the Korean translation by participating in the translation of transifex.
I'd appreciate if you check :
https://www.transifex.com/flo56958/minetinker/language/ko_KR/
thanks.

**Comment by Flo56958** [comment]
Thank you for the Translation! If you want to use the translation before the official update schedule you can download the nightly build off discord or download the yml-File and paste it in the lang folder.
