### ISSUE TITLE
Per modifier level cost

### ISSUE THREAD

**Issue by tankinnwow** [Flo56958/MineTinker#174]
**Is your feature request related to a problem? Please describe.**
The issue i am having is that i want to control the cost to apply a modifier. Haste 1 would cost $500 and Haste 2 would cost $1500. I need a way to control how fast players can max out there tools.

**Describe the solution you'd like**
Add a modifier cost for each level.

**Additional context**
Having the ability to control the money and xp cost per level for each modifier would allow for a lot more control for server owners. I am trying to build a prison server and i want to use this plugin but with access to unlimited materials maxing out a tool would take no time at all.

**Comment by Flo56958** [comment]
This can't be implemented into MineTinker as MT is not economy based. And every level is one item. You could however make a shop (with a plugin, if it exists) that increments the cost each time, and have no recipe for that modifier. If you have a different idea how to implement this feature, i happily reconsider. But it needs to be implementable with only MT features, so no money. A changeable crafting recipe isn't possible either. Only the enchant cost of modifiers could be increased. But not per tool but rather per modifier crafted.
