### ISSUE TITLE
Drilling Modifier Bug

### ISSUE THREAD

**Issue by katykat5099** [Flo56958/MineTinker#178]
I have a pick with Drilling 5 + Power 2 and i expect that it would mine a straight line of 2 x 2 and 5 blocks in but sometimes it will either mine two blocks only like power 1, sometimes it will mine in all sorts of random directions (like 5 blocks to the right and all the wrest 5 blocks in front) and it is just in general not really working properly. 

It's a bit hard to explain but i will try to explain based on questions.

**Comment by Flo56958** [comment]
I tried to improve that issue with the latest commit. Is it better on your end with the latest github version (available on the discord server)?

**Comment by Flo56958** [comment]
@katykat5099 ↑

**Comment by katykat5099** [comment]
Thanks for the mention. I’ll give it a try.

**Comment by katykat5099** [comment]
Okay so there does seem to be a difference right away. It is a lot more consistent, but the different angles problem persists. It worked almost perfectly when flying previously, but broke with max haste + beacon haste. But it seems to be more consistently the weird angles now even when digging slowly (flying)
