### ISSUE TITLE
Shovel breaks blocks that it shouldn't

### ISSUE THREAD

**Issue by xorinzor** [Flo56958/MineTinker#181]
**Describe the bug**
When you have the shovel with a Power 1 modifier it digs a 1x3 area.
If you have a chest in the area that is being dug, it will also destroy that chest and drop all the items.

**To Reproduce**
1. place down 3 blocks (S = sand C = chest) in a formation like this: S S C
2. dig the middle block
3. the chest will also get broken

**Expected behavior**
The expected behaviour would be that only the sand would be dug up. But since the Chest is not a block for which the shovel is the correct tool to break it, it should be left intact.

**Information about the server (please complete the following information):**
 - Plugin Version 1.6.2
 - Server Version: Paper 1.16.5-463
 - other Plugins

**Comment by xorinzor** [comment]
Just an update, the same happens too with a configuration like: planks - dirt - planks.

**Comment by Flo56958** [comment]
This is because they have similar hardness values. This is necessary as Power would not work for ores otherwise
