### ISSUE TITLE
Bug: shift clicking on a modifier item

### ISSUE THREAD

**Issue by Neo-TA** [Flo56958/MineTinker#186]
**Describe the bug**
Shift clicking on an modifier in /mt mods 1st GUI page puts it in hotbar or in the inventory.

**To Reproduce**
1. typed in /mt mod to open the GUI
2. highlighted over a modifier i wanted and shift clicked
4. appears on hotbar and or in inventory 
5. logged off and back on to see if its a visual glitch 
6. deop myself and tested again still the same thing 

**Expected behavior**
for the modifier not to be in the hotbar/inventory it doesnt do this when you click on a modifier to see the recipe then shift clicking.

**Screenshots**
N/A ill add if needed

**Information about the server (please complete the following information):**
 - latest one from the discord and the one from spigot page
 - 1.16
 - essentialsX
 - coreprotect
 - sleep-most

**Additional context**
no errors in console

**Comment by Flo56958** [comment]
Do you have op permissions @Neo-TA ? or the permission for the givemodifieritems command? Then this would be intended behaviour. Or do the Items disappear from the /mt mods gui?

**Comment by Neo-TA** [comment]
I feel a bit stupid sorry i gave myself "*" permissions in PEX to setup groups/permissions. Works as intended now after removing

Thanks
