### ISSUE TITLE
Coal Ore doesn't drop coal with Auto-Smelt Modifier

### ISSUE THREAD

**Issue by arnavsirigere** [Flo56958/MineTinker#187]
Coal ore doesn't drop coal after I mine it with a pickaxe that has the auto-smelt modifier. I get xp and hear the fire sound but don't get any coal out of it.

**Comment by Flo56958** [comment]
Auto-Smelt smelts coal into air (it burns it). If you want to change it you can edit the Auto-Smelt configuration.
