### ISSUE TITLE
MineTinker Conflict

### ISSUE THREAD

**Issue by subashton** [Flo56958/MineTinker#188]
Just thought I would let people know that MineTinker Conflicts with better-enchantments plugin(https://dev.bukkit.org/projects/better-enchantments) with you trying to add modifiers to your pre-existing tool to where you can no longer do it. I can't seem to find a fix for this. If there is a fix let me know and tell me how since these two plugins are cool when they work together.

**Comment by Flo56958** [comment]
@subashton It seems like the plugin uses the lore to save the options. MT can have the lore turned off in the config, but before you do that you can turn on the patternmatcher in layout.yml. Maybe it can fix that problem.

Sry for the late reply.

If the problem still persists with the lore of MT disabled, just reopen the issue.
