### ISSUE TITLE
Possible to control the range of the power modifier?

### ISSUE THREAD

**Issue by Hasunemiku2015** [Flo56958/MineTinker#190]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Not really a problem, but it is annoying when I need to switch between different sizes upon digging a tunnel.

**Describe alternatives you've considered**

Everytime when I need to dig something, I have to grind the entire pick down and add the modifiers back one by one, it is somewhat annoying when you have like 20 modifiers

**Additional context**

I would hope that it will be possible to hot-swap modifiers through a inventory gui/ cycle through different mining range by dropping the item on ground (just use the itemdropevent and then event.setcancelled()? )

For example , power 5 can do what power 1,2,3,4; power 3 can do 1,2,3
Higher level of power can dig the range of lower levels , not only 1*1 through shift (and it is very easy to forget to shift)

**Comment by Flo56958** [comment]
similar to #106
