### ISSUE TITLE
Grindstone not working

### ISSUE THREAD

**Issue by iExploze** [Flo56958/MineTinker#196]
In the config file of my server, I have the grindstone enabled and it is not working. and it keeps saying internal error when I try to disenchant some modifiers

1. get any tool/armour with modifiers
2. use it with a grindstone
3. see the internal error has occurred on the bottom

**Screenshots**
![Inked2021-06-17_22 15 45_LI](https://user-images.githubusercontent.com/54289660/122496519-eacaf100-cfb9-11eb-9902-b26022367084.jpg)

Server Information:
spigot 1.17
minetinker version 1.71 (newest)

**Comment by Flo56958** [comment]
Should be a bug caused by mc 1.17 and mt. Trying to fix it
