### ISSUE TITLE
Items enchanted with "minetinker" do not work with "deadchest" plugin

### ISSUE THREAD

**Issue by HighVoltage557** [Flo56958/MineTinker#198]
I have a plugin installed on my paper server called deadchest. https://dev.bukkit.org/projects/dead-chest
It puts the player's inventory in a chest when the player dies, but all items enchanted with the minetinker enchantments fall on the ground instead of going in the deadchest.

**Comment by Flo56958** [comment]
You need to disable Itembehaviour.ApplyOnPlayerDeath in the config to be compatible with that plugin, i think.
