### ISSUE TITLE
Can't apply modifiers

### ISSUE THREAD

**Issue by zanderwild** [Flo56958/MineTinker#2]
I place an iron pick with a modifier slot in the first slot and an enchanted cobweb in the other slot. All I get is the big red X

**Comment by Flo56958** [comment]
Do you place the modifier after the pick? Note that SilkTouch is not compatible with Luck and Auto-Smelt and can't be applied if one of the other is already on the tool. If you update the Plugin, modifiers that were created in a previous version seem to be not working anymore.
Is there a Error-report in the console when you are trying to modify the tool? If there is could you please send me that report if you have access to the console?

**Comment by MasterGordon** [comment]
I've got the same issue

**Comment by Flo56958** [comment]
It seems, that I can't recreate this issue myself... Is the enchanted Cobweb named "Silk-Touch-Modifier" (name in white). Is Silk-Touch enabled in the config? Note: You can't apply Silk-Touch on a Sword and Bow and it can only be applied once per tool.
If that is not the case: Try restarting the server

If the issue still occurs, please tell me exactly what you have done or how you get to this issue, so I can recreate it myself.

Thank you in advance!
Flo56958

**Comment by Flo56958** [comment]
In the latest update (a3) you need to write the exact name of your world in the config.yml (under AllowedWorlds). The default is world, world_nether, world_the_end as it is the standard naming scheme in Spigot. If you have more worlds or worlds with custom names you need to add them in the config (like the default ones) in order for the Plugin to work. (Elevators and Builderswands have their own AllowedWorlds-list)

**Comment by scaredycat3052** [comment]
having the same issue where i can not even with a non enchanted pick in the latest version of spigot it will not apply to the tool.

**Comment by Flo56958** [comment]
I can't help you when you give me like none information about what you are doing (please read the comments from me above and answer the questions in them). @zanderwild @MasterGordon @scaredycat3052

**Comment by Gorehid** [comment]
I have noticed that people who have been Sneak + Left Clicking into the anvil tend to fail at the addition of modifiers.

**Comment by zanderwild** [comment]
it works (sometimes) if you dont right click and shift click the items into the anvil slots

**Comment by Flo56958** [comment]
@zanderwild 
I have programmed it to be only a left click and you need to apply the modifier one at a time, as I noticed bugs when it was done otherwise. But I am working on a different solution.

Flo56958
