### ISSUE TITLE
Ausgewählte Modifier beim Level Up für Random Modifier

### ISSUE THREAD

**Issue by Sagutor** [Flo56958/MineTinker#214]
Hallo, ist es möglich, nur bestimmte Modifier auszuwählen, die bei einem Level Up als Random Modifier genommen werden sollen, also bei einer Spitzhacke zum Beispiel soll nur zwischen Haste,Luck,Unbreaking entschieden werden anstelle aller möglichen Modifier?

Wenn es da einen Code gibt dann kann ich den gern selbst einfügen, ich selbst bin da überfragt

**Comment by Flo56958** [comment]
Nein, zur Zeit werden alle erlaubten Modifier für den Random Modifier in Betracht gezogen. Konfigurierbar ist dies momentan nicht.
