### ISSUE TITLE
Directing Bugs

### ISSUE THREAD

**Issue by katykat5099** [Flo56958/MineTinker#216]
**Describe the bug**
Directing causes problems for some other enchantments such as Luck and Self Repair

**To Reproduce**
Have a tool such as a Pickaxe with Luck and Selfrepair
Use the pick as normal, and luck and self repair should behave as normal
Give the pick directing
Luck no longer works as well as self repair because directing just sends the exp to the exp bar and directing seems to ignore lucks modifiers.

**Expected behavior**
Directing should not ignore the other modifiers on the tool and prioritize them.

**Information about the server (please complete the following information):**
MineTinker version: MineTinker (1.7.2)
Server version: CraftBukkit version 3398-Spigot-f4ff00f-f3828bb (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
My Servers plugins currently: LuckPerms, ItemsXL, spark, ExplosionReversal, SilkSpawners, MineTinker, SkinsRestorer, ChatItem, Alchema, RHLeafDecay, HorseTpWithMe, mcMMO, floodgate, Vault, dynmap, Essentials, Multiverse-Core, Citizens, DiscordSRV, EssentialsChat, Geyser-Spigot, EssentialsSpawn, Harbor, Denizen, ServerTutorialPlus, DungeonsXL, Quests, GriefPrevention, Brewery

**Comment by Flo56958** [comment]
@katykat5099 so if I understand correctly you have enabled Mending (instead of the Plugins own effect) in the Self-Repair config?

**Comment by katykat5099** [comment]
I double checked with Luck and i think it may just be that we're incredibly unlucky + another plugging is not working with luck. On average you get way more with luck regardless if you have directing or not. I think. But the other issue with Self Repair is definitely not working properly.

**Comment by katykat5099** [comment]
Hi, another thing i noticed is that with Directing usually when you kill a mob like i said it goes to your EXP bar, but when you mine a ore the EXP drops on the ground like normal.

**Comment by Terminal-Access** [comment]
Confirming the bug with self repair on a tool/armor and mending being enabled via config, Having directing on a tool, that is then used to kill a mob that gives experiance, the mending effect is completely negated as the experiance goes directrly to the player's exp bar it dosent look like any checks are being done to see if any tools or armor the player is wearing or has equiped or in their offhand is checkd to see if it could be repaired prior to the exp being sent to the players expbar.

**Comment by Flo56958** [comment]
@Terminal-Access thank you for your reply. I completely lost track of this issue.

What I changed:
- Orbs now get teleported to the player position instead of adding them directly to the player
- Exp Directing now works with blocks as well

Hopefully these changes are helpful for Mending users

**Comment by Flo56958** [comment]
@katykat5099 I can't validate your finding with Luck. I've tested two Pickaxes with Luck 5 and the one with Directing had even more drops.
