### ISSUE TITLE
Directing DUPE when used with Keep Inventory 

### ISSUE THREAD

**Issue by nunavailabul** [Flo56958/MineTinker#220]
**Describe the bug**
When Keep inventory is on, Directing will still pull a players inventory from them when they are killed.  

Result: PVPer with Directing gets a dupe of the dead players inventory.

**To Reproduce**
1. Have Keep Inventory on
2. Player 1 has bow with Directing (havent tested other weapons)
3. Player 1 murders player 2
4. Player 1 has all of player 2's inventory drop at their feet/fill their inventory
5. Player 2 still has all of their inventory (keep Inventory is on)

**Expected behavior**
I would expect Directing to fail as with Keep Inventory on, there are no "drops"

**Information about the server (please complete the following information):**
 - Plugin Version 1.7.2
 - Server Version paper 235 (1.18.2-R0.1-SNAPSHOT)

**Comment by nunavailabul** [comment]
This is not resolved.  Did it auto close?

**Comment by Flo56958** [comment]
> This is not resolved. Did it auto close?

@nunavailabul Did you use the version on the Discord Server? Only the pre releases have the fix

**Comment by nunavailabul** [comment]
> > This is not resolved. Did it auto close?
> 
> @nunavailabul Did you use the version on the Discord Server? Only the pre releases have the fix

Ahh ty!  This is everyone's favourite plugin <3
