### ISSUE TITLE
Paper 1.19 Can't do enhancement to netherites!

### ISSUE THREAD

**Issue by Dirt233** [Flo56958/MineTinker#225]
**Describe the bug**

I can't add modules to the netherites equipment on 1.19paper

**To Reproduce**
1. Catch a netherite sowrd with lore of MineTinker
2. Use any moudles to add in the anvil GUI.
3.It show Can't use it on the tools 

**Expected behavior**
In recent version,it work properly.

**Screenshots**
![QQ截图20220704174935.png](https://s2.loli.net/2022/07/04/du78Fri4ZzLUTSO.png)

**Information about the server (please complete the following information):**
 - Plugin Version: 1.7.2
 - Server Version: 1.19 paper (latest development)
 - other Plugins(like before)

**Additional context**
NOPE

**Comment by Flo56958** [comment]
You can find 1.19 preview versions on the discord server or here on github. The 1.19 Patch is not released yet.
