### ISSUE TITLE
language missing

### ISSUE THREAD

**Issue by KaiZe02** [Flo56958/MineTinker#247]
there is some item missing in translate file  ex: EnderEye, GoldenApple, BookShelf, LimeDye.....

**Comment by Flo56958** [comment]
Some language files are incomplete.
Which language are you using @KaiZe02?

**Comment by KaiZe02** [comment]
zh_tw, I translate the modifier by using en_us file.

**Comment by Flo56958** [comment]
The languages are community translated. Most of them are only partially finished. If you like you can help translate: 
https://app.transifex.com/flo56958/minetinker/dashboard/

When the language is fully translated it will be automatically updated in this repo and a jar file will be uploaded to the discord server.

**Comment by KaiZe02** [comment]
I mean the translate for item like this: [[https://imgur.com/a/2A0kQYJ](url)](https://imgur.com/a/2A0kQYJ)

**Comment by Flo56958** [comment]
These words are from the Minecraft Items. I do not think that there is a way to change that.
