### ISSUE TITLE
Anvil Bug

### ISSUE THREAD

**Issue by scooterwolfie** [Flo56958/MineTinker#258]
**Describe the bug**
Cannot use enchantment books in anvil, plugin just cancels them out.

**To Reproduce**
![image](https://github.com/Flo56958/MineTinker/assets/149985472/512705b6-2f1e-420c-b882-df3e1bc88a23)

**Information about the server (please complete the following information):**
 - Plugin Version: Lastest
 - Server Version: 1.19.4
 - other Plugins:
![image](https://github.com/Flo56958/MineTinker/assets/149985472/eb3f298f-c76b-41bd-aadb-ac2568a4d425)

**Comment by scooterwolfie** [comment]
Same behavior with enchantment tables.

**Comment by Flo56958** [comment]
@scooterwolfie This is by design. The plugin replaces the enchantment system. If you still want to use it you need to enable AllowEnchanting in the main config.

```
AllowEnchanting: false                #When enabled you can enchant the tools with vanilla methods (not recommended!)
EnchantingCostsSlots: true            #When enchanted through the enchanting table or anvil (the vanilla way) should the tool need free slots
ConvertBookToModifier: true           #Should right clicking a bookshelf with an enchanted book convert enchantments to modifier items
ConvertEnchantmentsOnEnchant: true    #Should (new) enchantments be converted to modifiers when tools are enchanted
RefundLostEnchantmentsAsItems: true   #If you want to enchant Sharpness 5 on a tool but MT only allows Sharpness 4 it will drop one Sharpness-Modifier (ConvertEnchantmentsOnEnchant needs to be true)
ConvertEnchantsAndAttributes: true    #Should enchants and Attributes be also converted if tool is converted
```

All Enchantments have a corresponding modifier and you can convert enchanting books by right-clicking a bookshelf.

**Comment by scooterwolfie** [comment]
Ohhh, gotcha. Thanks for the information!
