### ISSUE TITLE
Crossbow Bug (Piercing)

### ISSUE THREAD

**Issue by scooterwolfie** [Flo56958/MineTinker#260]
After adding Piercing to my crossbow, it will load up and no longer shoot. No arrow comes out of the bow.

![image](https://github.com/Flo56958/MineTinker/assets/149985472/503ec8dc-bdc2-4ca6-97b1-87690f03cc70)

![image](https://github.com/Flo56958/MineTinker/assets/149985472/3d67acc3-e8e6-4645-b53c-63e00536735b)

**Comment by Flo56958** [comment]
So i tested it on my end but i cannot replicate the problem. It could be something with the other plugins you have installed. mcMMO had some incompatibilities. You can try to enable the pattern matcher in layout.yml.
