### ISSUE TITLE
Cannot "Shift Click" items into or out of Grindstone

### ISSUE THREAD

**Issue by lpjn** [Flo56958/MineTinker#266]
**Describe the bug**
Cannot "Shift Click" items into or out of Grindstone

**To Reproduce**
Steps to reproduce the behaviour:
1. Place Grindstone
2. Spawn in MineTinkers sword
3. Shift click into and out of grindstone does not work. manual pick up and placement does work

**Expected behavior**
Shift click should place the item into the appropriate slot

**Screenshots**
![grind](https://github.com/Flo56958/MineTinker/assets/38690189/38e545f2-77a1-40d5-8e44-20bfd32b8cb8)

**Information about the server (please complete the following information):**
 - 2024-01-24_18-59_commit_2b9d62
 - paper-1.20.4-382
 - Plugins: Essentials, FastAsyncWorldEdit, MineTinker, ViaBackwards, ViaVersion

**Additional context**
No console errors

**Comment by lpjn** [comment]
Hey @Flo56958 thanks for this! However I noticed that after updating to the build above, I still see the issue. Any advice?

**Comment by Flo56958** [comment]
Hi @lpjn, the grindstone rejects all tools without any modifiers or enchantments. I'll change that behavior so only the result is blocked.

**Comment by Flo56958** [comment]
It should now work with tools that do not have any modifiers on them as well.

**Comment by lpjn** [comment]
Looking good! Nice one
