### ISSUE TITLE
trident spawned with Inifnity II listed in tool tip - but no loyalty.

### ISSUE THREAD

**Issue by nunavailabul** [Flo56958/MineTinker#267]
**Describe the bug**
Loot dropped trident had Infinity II on it, but no actual loyalty enchant, maybe becuase there is no level 2?

**Expected behavior**
Infinity on dropped/upgarded items to be max level 1

**Information about the server (please complete the following information):**
 - Plugin Version 1.9
 - Server Version 1.20.4 (paper-550)

**Server Plugins (68):**
 Paper Plugins:
  - BKCommonLib, WolfyUtilities
 Bukkit Plugins:
  - ajParkour, ArmorStandTools, Bank, BetterStructures, BottledExp, Brewery, BungeeTabListPlus, ChestSort, Citizens, CMILib
  Core, CraftBook, CurseOfVanishing, CustomCrafting, CustomWings, DecentHolograms, DeluxeMenus, DiscordSRV, DiscoverWarps, EliteMobs
  ExtraContexts, floodgate, GCore, GDHooks, GriefDefender, GSit, GSlotMachine, Harbor, Hat, HeadDatabase
  *Herochat, ILibrary, InsaneShops, InventoryRollbackPlus, ItemEdit, Jobs, LibsDisguises, LinkedEnderchest, LuckPerms, MessageAnnouncer
  MineTinker, ModelEngine, Multiverse-Core, MyCommand, MyDog, PlaceholderAPI, Plan, PocketGames, ProtocolLib, RealEstate
  ResurrectionChest, ServerRestart, spark, Train_Carts, UberEnchant, UltimateCatcher, UltimateFishing, UltraEconomy, Vault, ViaVersion
  VoidGen, WanderingTrades, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Additional context**
Item dropped from mob kill and had infinity 2 already on it.  Trident did not return.  Using uberEnchant I looked at udel (removes enchants already on item) there was no entry for loyalty/infinity on the item.

**Comment by Flo56958** [comment]
Infinity 2 is loyalty 2 for tridents. The trident should have the loyalty 2 enchant on it.

**Comment by Flo56958** [comment]
Closed until further information.

**Comment by nunavailabul** [comment]
Sorry Flo!  I completely forgot about this.  No there are no other plugins that have disabled enchants. 

- I use MineTinker to disable enchanting to force players to use Minetinker Modifiers.  
- This is a weapon introduced/dropped in loot via Elite Mobs (MagmaGuy).

**Comment by Flo56958** [comment]
Could be an issue with the custom drop events of that plugin in combination with MT events.
