### ISSUE TITLE
Broken Shears can be used on beehives&nest an infinite amount of times.

### ISSUE THREAD

**Issue by jacklollz2** [Flo56958/MineTinker#269]
If you use broken shears, when you have "protect tool" enabled, you can still shear beehives&nests even if there isn't enough durability. You get the honeycomb and the tool doesn't break. Infinite uses.

**Comment by Flo56958** [comment]
@jacklollz2
I tried to recreate this problem and it it did not work. The honey extraction was cancelled when the shears were at low durability. (They were destroyed when used with a dispenser).

Do you have other plugins that overwrite this cancelation? Or is there a certain requirement to trigger this?
