### ISSUE TITLE
Crafting grid recipes do not work

### ISSUE THREAD

**Issue by Gorehid** [Flo56958/MineTinker#3]
Version: a3
World: world

I am not certain if I'm missing something, but none of the recipes using the crafting grid work. For example the [https://github.com/Flo56958/MineTinker/wiki/Modifiers#luck](Luck) modifier creation does not seem to create the modifier. It does not even show the modifier item. This also includes things like the new builders wands.

**Comment by Flo56958** [comment]
@Gorehid In the config there is the option "logging - debug". If you turn this on you can see if the recipes can register at startup. If they can't a red message will appear on plugin startup in the console. Do they appear or does the plugin start normal with debug turned on?

**Comment by Gorehid** [comment]
The only thing I see in the log are the following lines:
[14:16:19] [Server thread/INFO]: [MineTinker] Enabling MineTinker va3
[14:16:19] [Server thread/INFO]: [MineTinker] Started Metrics-service! Thank you for enabling it in the config! It helps to maintain the Plugin and fix bugs. (Data is anonymously sent)
[14:16:19] [Server thread/INFO]: [MineTinker] Debug logging is enabled! You should disable it in the config!
[latest.log](https://github.com/Flo56958/MineTinker/files/2241523/latest.log)

**Comment by Flo56958** [comment]
@Gorehid 
I see that you have Multiverse-Core installed! By default the config file is only configured on the worlds 'world', 'world_nether', 'world_end'! If you have named your other worlds differently just replace the worldnames in the config.yml (under folder Plugins/MineTinker) under AllowedWorlds (as well as in Elevator and Builderswands). But that should not interfere with the crafting recipes. The only thing i can imagine is that it is a compatibility issue with your other installed plugins (i myself have not tested MineTinker with other plugins). Do you know of a Plugin that manipulates crafting recipes? It also could be that some plugins are not ported to 1.13 and hence MineTinker not working correctly.

Flo56958

Edit: I have installed a few plugins myself, but can't seem to recreate your problem. All recipes load correctly. (I've installed Multiverse, Vault, TreeAssist, Arconix, CoreProtect, GriefPrevention)

Just to be sure: You are crafting the Luck-Modifier like this:
![luck-recipe](https://user-images.githubusercontent.com/13511426/43406481-9a57ac94-941c-11e8-8529-885a2e166683.JPG)

**Comment by Gorehid** [comment]
The Multiverse-Core world has been set up in the MineTinker config.

As far as I know, none of the plugins installed manipulate the crafting recipes.

[https://puu.sh/B5Gni/5a215ac2a6.png](Luck-Modifier)

**Comment by Gorehid** [comment]
So, I've spent the time going through each plugin we have, and turned them off one at a time. I finally found that MobHunting has the issue with MineTinker. I have no idea why it has the issue. After turning every plugin back on except for MobHunting, MineTinker's crafting recipes work perfectly.

**Comment by Flo56958** [comment]
@Gorehid 
I have change (a bit) in the crafting recipes code in version a6. It could be that MobHunting is now compatible but I did not test it. I mentioned the incompatibility on the spigotmc.org-Page of the Plugin.
If MobHunting is now compatible, I would be more than thankful if you could test it and tell me.

Sincerely,
Flo56958
