### ISSUE TITLE
Adding Slimefun Integration

### ISSUE THREAD

**Issue by pontaoski** [Flo56958/MineTinker#36]
Title says it all. The bare minimum would be adding recipes to the research book, which is easy and wouldn't take much effort to enable/disable calling the API to add recipes depending on if Slimefun is on the server or not. You could also decide to go the extra mile and require research in Slimefun a la TinkerTools for things, as well as requiring a custom crafting place, but that would require changes to the code elsewhere, most likely.

**Comment by Flo56958** [comment]
Add a hook into the Slimefun API

**Comment by Flo56958** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/wiki/API
