### ISSUE TITLE
hammer/excavator feature

### ISSUE THREAD

**Issue by jinkhya** [Flo56958/MineTinker#4]
**Is your feature request related to a problem? Please describe.**
It usually takes a lot of time to clear a large area
**Describe the solution you'd like**
A pickaxe and a shovel with some kind of modifier that mines 3*3

It'd be like hammers and Excavators from tinkers :)

**Comment by Flo56958** [comment]
@jinkhya 
### This feature is already implemented!

There is a Power-Modifier for Axes/Pickaxes/Shovels. Just right-click a bookshelf with an emerald and you get a Power-Modifier-Item. 

Power 1 will break 3x1 blocks horizontally
Power 2 will break 3x3 blocks
Power 3 is not implemented yet but planned to break 5x5 blocks

**Comment by jinkhya** [comment]
oh sorry, I missed it in the description of modifiers, or just didn't understand that it's what it did. Awesome plugin !!
