### ISSUE TITLE
Missing modifiers for some vanilla enchantments

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#47]
The following enchantments do not have modifier equivalents:

- [x] Bane of Anthropods
- [x] Smite
- [x] Fire Protection
- [x] Blast Protection
- [x] Projectile Protection
- [x] Thorns
- [x] Channeling
- [x] Multi-Shot
- [x] Piercing
- [x] Quick-Charge

**Comment by Flo56958** [comment]
![image](https://user-images.githubusercontent.com/13511426/59164342-bccd8f00-8b0b-11e9-8f8a-387e382afd7f.png)

**Comment by Draycia** [comment]
Modifier Item ideas:

- Fermented Spider Eye for Bane of Anthropods
- Bone for Smite

**Comment by Draycia** [comment]
Modifier Name ideas:

- Unholy Bone for Smite

**Comment by Draycia** [comment]
Sharpness and Protecting should also be modified to include optional incompatibility with similar modifiers, just like vanilla.

**Comment by Draycia** [comment]
@Flo56958 How do you feel about the modifier for Bane of Arthropods being called `Spider's Bane`?

**Comment by Flo56958** [comment]
> @Flo56958 How do you feel about the modifier for Bane of Arthropods being called `Spider's Bane`?

Sounds good
