### ISSUE TITLE
Custom Names

### ISSUE THREAD

**Issue by Juessa** [Flo56958/MineTinker#5]
Hi, I would like to use this plugin in a Spanish server so, I want to know if you can add the option to custom the names of the option please and thank you.

**Comment by Flo56958** [comment]
@Juessa 
Modifiers and Modifier-Items can have custom names through the config in version a4.
### Note: this will break all already crafted modifiers and modified tools! (If you change it)

Flo56958

**Comment by Juessa** [comment]
Thank you so much :D

**Comment by Juessa** [comment]
Thank you so much :D
