### ISSUE TITLE
Config option to change the recipe of MineTinker tools

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#54]
~~Lets player choose whether or not the tools they craft are MineTinker ones or not.~~

Helps let server owners decide how MT tools are obtained

**Comment by Draycia** [comment]
Optionally just have an option to disable the automatic conversion on craft.

The ability to convert tools into blank MineTinker ones via crafting already exists.

**Comment by Flo56958** [comment]
The option to disable crafting is already implemented.
