### ISSUE TITLE
Better handling of Enchantment and Modifier combinations

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#58]
When enchanting of MT items is enabled, and the item has Sharpness 3, if you go to add the Sharpness modifier, the enchantment level goes to 1. 

Possibly add an option to auto convert the enchantment to the Modifier, so that the item would become Sharpness 4, instead of Sharpness 1.

**Comment by Flo56958** [comment]
- [ ] Implement a check in the specific Modifier class and add a function to add more than one level at a time.

**Comment by Flo56958** [comment]
Should be possible with a new conversion command

**Comment by Draycia** [comment]
Added an experimental implementation, assuming bukkit calls the event when I think it does.

**Comment by Flo56958** [comment]
Adding a check to the applyMod function to check if the item is already enchanted and reacting accordingly
