### ISSUE TITLE
Make Directing work correctly with the BlockBreakEvent

### ISSUE THREAD

**Issue by Flo56958** [Flo56958/MineTinker#59]
- [ ] Get the correct drops from the event
- [ ] Make Directing applicable to pickaxes and others

**Comment by Draycia** [comment]
One solution could be to have a Vacuum modifier, whenever blocks are broken, all items near the player are vacuum'd in towards the player so they pick them up.

**Comment by Flo56958** [comment]
> One solution could be to have a Vacuum modifier, whenever blocks are broken, all items near the player are vacuum'd in towards the player so they pick them up.

like the Magnetic Modifier from TConstruct
> "Magnetic: Pulls in items from ~2 blocks away when used."
from: https://tinkers-construct.fandom.com/wiki/Material_Stats
