### ISSUE TITLE
Modifier options and configs?

### ISSUE THREAD

**Issue by kohlth** [Flo56958/MineTinker#66]
~~1. setting to switch the extra modifier modifier to a special "token" (sunflower with nbt) so if theres any conflict with nether stars on the server and gives the ability to have crafting recipes for the modifiers~~

- [ ] 2. option to have diffrent teir tokens that add more open modifiers (lets you apply more than one open modifier in one anvil craft) and possibly add tokens that have pre set modifiers (like a token that gives the max beheading or a token that gives max sharpness at configurable open modifier costs)

- [ ] 3. option to have a crafting recipe for "tokens" (8 diamonds and a gold block default?) and ability to change recipe of it

- [x] 4. option and configs to let vanilla mobs drop tokens with settable rates and token amounts (like over-world aggressive mobs have a 0.1% chance and the wither and nether dragon drop 2 at 100% chance)

- [x] 5. option for random modifier drops from mobs?

- [x] 6. option to have tools gain a random modifier(s) along with or instead of the open modifier space upon level up?

~~7. option to not gain modifiers on level up~~

~~8. option to gain more (x) modifiers on level up~~

~~9. option to not have level ups~~

~~10. option for tools to not be crafted automatically to mine-tinker tools on default but have to have a token or nether star, or a configed item applyed in a anvil to make it a minetinker tool, maybe apply this to the elytra and trident?~~

~~11. option to have soulbound remove its self from your tool when you die~~

~~12. option to have non vanilla max enchants? and how high to you can go?~~

i hope these are good suggestions and cant wait to see what you do with them

**Comment by Draycia** [comment]
1. You can change the item that each modifier is, including the Extra-Modifier, with the `modifier_item` settings.
7.  This can be disabled in `config.yml`

```
LevelUpEvents:
  enabled: true
  RandomModifier:
    enabled: true
    percentage: 10
```

10. The setting for this should be `AllowCrafting` in `config.yml`
12. The max level should be configurable for each modifier, I'm unsure what happens when you set a modifier's max level to be above the enchantment's vanilla cap though.

**Comment by kohlth** [comment]
alright got it (i saw the other issues with the config for the plugin right after i submited this one my bad)

**Comment by Flo56958** [comment]
2 & 3: Sounds like a good overhaul for the Extra Modifier.

5: looks like a duplicate from #49 (with 4 included if 2 and 3 are implemented)

9: Do we need a explizit option for that? You could change all the exp values (and EnableDamageExp) to 0 or false. Or the LevelStep to a negative value. [To the options](https://github.com/Flo56958/MineTinker/blob/alpha/core/src/main/resources/config.yml#L17)

11: Soulbound should not be removed when used when [DecrementModLevelOnUse](https://github.com/Flo56958/MineTinker/blob/alpha/core/src/main/java/de/flo56958/MineTinker/Modifiers/Types/Soulbound.java#L84) is false.
