### ISSUE TITLE
[idea/suggestion] more tool materials

### ISSUE THREAD

**Issue by kohlth** [Flo56958/MineTinker#70]
mine-tinker is pretty cool and has alot of modifiers and cool functionality with its tools but i think its missing a thing or two, mainly, different tool materials
sure you have the four that come in the game but theres only one best one for all tools and armors (diamond) 

if there where better materials that material specific attributes it could really bring more to the plugin

possible crafting method by right clicking a diamond block with items in both your main and off hand??, exp cost?? (maybe have the ability to make chains for chain link armor??) (make phantom membrane with ender pearl and leather?

possible use of custom damage values and textures for materials and pickaxes?

ideas for materials
armor:

- living hide: made from rotten flesh and leather on a diamond block , this slightly weaker in the protection department leather armor repairs its self over time and gives some regeneration too you,( living hide can be used to make a regeneration modifier??)

- diamond scute; made from diamonds and turtle scute, has 9 shirts of  protection and gives you water breathing underwater along with max levels of aqua affinity, depth strider, and respiration, it will not allow you to apply fiery

elytra: (costs 6 or 8 of a material)
diamantine membrane: diamond + phantom membrane
- gives elytra a actual base protection level of diamond 

theres more ideas for tools and stuff but it would take too long to type it out  and maybe you guys have better ideas than me, anyways i hope you enjoy this one , more ideas in the future promised (i find making these fun somehow)

**Comment by Flo56958** [comment]
I am not sure how good "new" materials can be implemented as you cant (simply) add new materials with the spigot api because it needs to be a vanilla server.

**Comment by kohlth** [comment]
i was thinking like slimefun did where they made already existing items have nbt that made them unusable regularly and only for the slime fun plugin
