### ISSUE TITLE
Enchantments are hard coded twice in each modifier

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#73]
In the `removeMod` methods, it might be better to call `getAppliedEnchantments` and remove those, instead of hard coding the enchantments in both methods.

**Comment by Flo56958** [comment]
`getAppliedEnchantment` return a List and `removeMod` can iterate over it -> `removeMod` does not need to be overwritten by the specific Modifier and can be not abstract in the Modifier-Class

**Comment by Draycia** [comment]
Done
