### ISSUE TITLE
Allow players to control the orientation of Power 1

### ISSUE THREAD

**Issue by Draycia** [Flo56958/MineTinker#82]
**Is your feature request related to a problem? Please describe.**
No. Simply want to encourage using different power levels for different situations.

**Describe the solution you'd like**
Changing hotbar slots (scrolling) while holding shift would change between 1x3 and 3x1 mode.

An actionbar message would be sent saying the new orientation.

Wouldn't need to be persisted across restarts but that would be nice.

**Describe alternatives you've considered**
N/A

**Comment by kohlth** [comment]
holding shift and using f or  the "put tool in off hand button" to toggle the options instead maybe? idk if this would be easier or harder to code up

**Comment by Flo56958** [comment]
well the vertical option is in the config but not controllable by the players themselves

**Comment by Draycia** [comment]
Temporary implementation in 2b2897373ae8d6aedfe018501572d0a7d54a6460
