### ISSUE TITLE
Not Possible to create MineTinkerTools with NBT Tags

### ISSUE THREAD

**Issue by mono323** [Flo56958/MineTinker#93]
I am using the Spigot plugin Smeltery to add custom smelting to my server but this plugin uses a NBT Tag plugin to create those so my question now is... would it be possible to add items with NBT Tags to MineTinker?

**Comment by Flo56958** [comment]
you can add nbt tags with other plugins to the plugin. if the item has nbt tags before converting it will stay on the item
